// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ6zSbOsY2KSHuyp2vvV4ksNMrO4UtVfc',
    appId: '1:895089276635:android:49314843600407edcabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    storageBucket: 'parchese-pop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5CwUvJU85a23cK68liMVhQDG9cVFM8Q',
    appId: '1:895089276635:ios:3d2c492018cdf682cabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    storageBucket: 'parchese-pop.firebasestorage.app',
    iosBundleId: 'com.liisgo.parchesepop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH5CwUvJU85a23cK68liMVhQDG9cVFM8Q',
    appId: '1:895089276635:ios:3d2c492018cdf682cabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    storageBucket: 'parchese-pop.firebasestorage.app',
    iosBundleId: 'com.liisgo.parchesepop',
  );

  /// Firebase does not provide a first-party Windows app registration through
  /// the FlutterFire CLI. The Windows Firebase C++ plugins accept the web app
  /// credentials for the same project, which keeps anonymous Auth and
  /// Realtime Database on the exact same backend as Android, iOS and macOS.
  /// The database URL is explicit because desktop builds do not read a native
  /// Google services file.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmAHegM43lv-1AMUCWzBvI6HyWqMgVev4',
    appId: '1:895089276635:web:5420d300a8d1b36bcabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    databaseURL: 'https://parchese-pop-default-rtdb.firebaseio.com',
    storageBucket: 'parchese-pop.firebasestorage.app',
    authDomain: 'parchese-pop.firebaseapp.com',
    measurementId: 'G-4RZWS75J32',
  );
}
