// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ6zSbOsY2KSHuyp2vvV4ksNMrO4UtVfc',
    appId: '1:895089276635:android:49314843600407edcabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    storageBucket: 'parchese-pop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5CwUvJU85a23cK68liMVhQDG9cVFM8Q',
    appId: '1:895089276635:ios:3d2c492018cdf682cabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    storageBucket: 'parchese-pop.firebasestorage.app',
    iosBundleId: 'com.liisgo.parchesepop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH5CwUvJU85a23cK68liMVhQDG9cVFM8Q',
    appId: '1:895089276635:ios:3d2c492018cdf682cabefe',
    messagingSenderId: '895089276635',
    projectId: 'parchese-pop',
    storageBucket: 'parchese-pop.firebasestorage.app',
    iosBundleId: 'com.liisgo.parchesepop',
  );
}
