import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import 'firebase_options.dart';
import 'game_engine.dart';

enum MatchPlayType { online, cpu }

enum MatchLaunchSource { home, rematch }

enum CpuDifficulty { easy, normal, expert }

/// Optional opaque references used to correlate anonymous analytics events.
///
/// These values must be generated by the app. They must never contain an email,
/// player name, phone number, advertising identifier, or Firebase user id. They
/// are intentionally logged as event parameters instead of user properties.
@immutable
class AnalyticsCorrelation {
  const AnalyticsCorrelation({this.anonymousMatchId, this.anonymousSessionId});

  final String? anonymousMatchId;
  final String? anonymousSessionId;

  Map<String, Object> get parameters {
    final result = <String, Object>{};
    if (anonymousMatchId case final value?) {
      result['match_ref'] = _validatedAnonymousReference(
        value,
        'anonymousMatchId',
      );
    }
    if (anonymousSessionId case final value?) {
      result['app_session_ref'] = _validatedAnonymousReference(
        value,
        'anonymousSessionId',
      );
    }
    return result;
  }
}

/// Shared, non-identifying context for events that belong to a match.
@immutable
class MatchAnalyticsContext {
  const MatchAnalyticsContext({
    required this.playType,
    required this.mode,
    this.correlation = const AnalyticsCorrelation(),
  });

  final MatchPlayType playType;
  final GameMode mode;
  final AnalyticsCorrelation correlation;

  Map<String, Object> get parameters => <String, Object>{
    'play_type': playType.name,
    'game_mode': _gameModeName(mode),
    ...correlation.parameters,
  };
}

/// A typed event that can be sent to the game's analytics destination.
abstract interface class GameAnalyticsEvent {
  String get eventName;

  Map<String, Object> get parameters;
}

@immutable
class MatchStartEvent implements GameAnalyticsEvent {
  const MatchStartEvent({
    required this.playType,
    required this.mode,
    this.launchSource = MatchLaunchSource.home,
    this.cpuDifficulty,
    this.matchmakingWaitSeconds,
    this.fallbackOpponentCount,
    this.liveHumanOpponentCount,
    this.takenOverOpponentCount,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(
         playType == MatchPlayType.cpu || cpuDifficulty == null,
         'Online matches cannot include a CPU difficulty.',
       ),
       assert(
         playType == MatchPlayType.online ||
             (matchmakingWaitSeconds == null &&
                 fallbackOpponentCount == null &&
                 liveHumanOpponentCount == null &&
                 takenOverOpponentCount == null),
         'CPU matches cannot include online matchmaking metrics.',
       ),
       assert(matchmakingWaitSeconds == null || matchmakingWaitSeconds >= 0),
       assert(fallbackOpponentCount == null || fallbackOpponentCount >= 0),
       assert(liveHumanOpponentCount == null || liveHumanOpponentCount >= 0),
       assert(takenOverOpponentCount == null || takenOverOpponentCount >= 0);

  final MatchPlayType playType;
  final GameMode mode;
  final MatchLaunchSource launchSource;
  final CpuDifficulty? cpuDifficulty;
  final int? matchmakingWaitSeconds;
  final int? fallbackOpponentCount;
  final int? liveHumanOpponentCount;
  final int? takenOverOpponentCount;
  final AnalyticsCorrelation correlation;

  bool get isRematch => launchSource == MatchLaunchSource.rematch;

  @override
  String get eventName => switch (playType) {
    MatchPlayType.online => 'online_match_started',
    MatchPlayType.cpu => 'cpu_match_started',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      'play_type': playType.name,
      'game_mode': _gameModeName(mode),
      'is_rematch': isRematch ? 1 : 0,
      'launch_source': launchSource.name,
      ...correlation.parameters,
    };
    if (cpuDifficulty case final value?) {
      result['cpu_difficulty'] = value.name;
    }
    if (matchmakingWaitSeconds case final value?) {
      result['matchmaking_wait_seconds'] = value;
    }
    if (fallbackOpponentCount case final value?) {
      result['fallback_opponent_count'] = value;
    }
    if (liveHumanOpponentCount case final value?) {
      result['live_human_opponent_count'] = value;
    }
    if (takenOverOpponentCount case final value?) {
      result['taken_over_opponent_count'] = value;
    }
    return result;
  }
}

@immutable
class MatchFirstRollEvent implements GameAnalyticsEvent {
  const MatchFirstRollEvent({
    required this.match,
    required this.secondsFromMatchStart,
    this.turnNumber = 1,
    this.diceCount = 2,
  }) : assert(secondsFromMatchStart >= 0),
       assert(turnNumber > 0),
       assert(diceCount > 0);

  final MatchAnalyticsContext match;
  final int secondsFromMatchStart;
  final int turnNumber;
  final int diceCount;

  @override
  String get eventName => 'match_first_roll';

  @override
  Map<String, Object> get parameters => <String, Object>{
    ...match.parameters,
    'seconds_from_match_start': secondsFromMatchStart,
    'turn_number': turnNumber,
    'dice_count': diceCount,
  };
}

enum MatchCompletionReason { reachedHome, forfeit, timeout }

@immutable
class MatchCompletedEvent implements GameAnalyticsEvent {
  const MatchCompletedEvent({
    required this.match,
    required this.reason,
    this.placement,
    required this.durationSeconds,
    required this.turnsPlayed,
  }) : assert(placement == null || (placement >= 1 && placement <= 4)),
       assert(durationSeconds >= 0),
       assert(turnsPlayed >= 0);

  final MatchAnalyticsContext match;
  final MatchCompletionReason reason;
  final int? placement;
  final int durationSeconds;
  final int turnsPlayed;

  @override
  String get eventName => 'match_completed';

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...match.parameters,
      'completion_reason': reason.name,
      'duration_seconds': durationSeconds,
      'turns_played': turnsPlayed,
    };
    if (placement case final value?) result['placement'] = value;
    return result;
  }
}

enum MatchAbandonReason { backButton, appClosed, inactivity, disconnect, other }

@immutable
class MatchAbandonedEvent implements GameAnalyticsEvent {
  const MatchAbandonedEvent({
    required this.match,
    required this.reason,
    required this.secondsPlayed,
    required this.turnsPlayed,
  }) : assert(secondsPlayed >= 0),
       assert(turnsPlayed >= 0);

  final MatchAnalyticsContext match;
  final MatchAbandonReason reason;
  final int secondsPlayed;
  final int turnsPlayed;

  @override
  String get eventName => 'match_abandoned';

  @override
  Map<String, Object> get parameters => <String, Object>{
    ...match.parameters,
    'abandon_reason': reason.name,
    'seconds_played': secondsPlayed,
    'turns_played': turnsPlayed,
  };
}

enum MatchResumeStage { attempted, succeeded, failed }

enum MatchResumeFailureReason { missingSave, invalidSave, expired, other }

@immutable
class MatchResumeEvent implements GameAnalyticsEvent {
  const MatchResumeEvent({
    required this.match,
    required this.stage,
    this.secondsAway,
    this.failureReason,
  }) : assert(secondsAway == null || secondsAway >= 0),
       assert(
         stage == MatchResumeStage.failed || failureReason == null,
         'Only a failed resume can include a failure reason.',
       );

  final MatchAnalyticsContext match;
  final MatchResumeStage stage;
  final int? secondsAway;
  final MatchResumeFailureReason? failureReason;

  @override
  String get eventName => switch (stage) {
    MatchResumeStage.attempted => 'match_resume_attempted',
    MatchResumeStage.succeeded => 'match_resumed',
    MatchResumeStage.failed => 'match_resume_failed',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{...match.parameters};
    if (secondsAway case final value?) {
      result['seconds_away'] = value;
    }
    if (failureReason case final value?) {
      result['resume_failure_reason'] = value.name;
    }
    return result;
  }
}

enum RematchStage { offered, started, declined }

@immutable
class RematchEvent implements GameAnalyticsEvent {
  const RematchEvent({required this.match, required this.stage});

  final MatchAnalyticsContext match;
  final RematchStage stage;

  @override
  String get eventName => switch (stage) {
    RematchStage.offered => 'rematch_offered',
    RematchStage.started => 'rematch_started',
    RematchStage.declined => 'rematch_declined',
  };

  @override
  Map<String, Object> get parameters => match.parameters;
}

enum TutorialStage { started, stepCompleted, skipped, completed }

enum TutorialStep {
  firstRoll,
  releaseToken,
  chooseMove,
  safeSquare,
  capture,
  reachHome,
}

@immutable
class TutorialEvent implements GameAnalyticsEvent {
  const TutorialEvent({
    required this.stage,
    this.step,
    this.elapsedSeconds,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(elapsedSeconds == null || elapsedSeconds >= 0),
       assert(
         stage != TutorialStage.stepCompleted || step != null,
         'A completed tutorial step must identify the step.',
       );

  final TutorialStage stage;
  final TutorialStep? step;
  final int? elapsedSeconds;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (stage) {
    TutorialStage.started => 'tutorial_started',
    TutorialStage.stepCompleted => 'tutorial_step_completed',
    TutorialStage.skipped => 'tutorial_skipped',
    TutorialStage.completed => 'tutorial_completed',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{...correlation.parameters};
    if (step case final value?) {
      result['tutorial_step'] = value.name;
    }
    if (elapsedSeconds case final value?) {
      result['elapsed_seconds'] = value;
    }
    return result;
  }
}

enum RewardedAdStage {
  offered,
  started,
  completed,
  declined,
  unavailable,
  failed,
}

enum RewardedAdPlacement { shopCoins, postMatchReward }

@immutable
class RewardedAdEvent implements GameAnalyticsEvent {
  const RewardedAdEvent({
    required this.stage,
    required this.placement,
    this.rewardCoins,
    this.match,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(rewardCoins == null || rewardCoins > 0);

  final RewardedAdStage stage;
  final RewardedAdPlacement placement;
  final int? rewardCoins;
  final MatchAnalyticsContext? match;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (stage) {
    RewardedAdStage.offered => 'rewarded_ad_offered',
    RewardedAdStage.started => 'rewarded_ad_started',
    RewardedAdStage.completed => 'rewarded_ad_completed',
    RewardedAdStage.declined => 'rewarded_ad_declined',
    RewardedAdStage.unavailable => 'rewarded_ad_unavailable',
    RewardedAdStage.failed => 'rewarded_ad_failed',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...correlation.parameters,
      if (match case final value?) ...value.parameters,
      'ad_placement': placement.name,
    };
    if (rewardCoins case final value?) {
      result['reward_coins'] = value;
    }
    return result;
  }
}

enum CurrencyFlow { earned, spent }

enum CurrencySource {
  matchCompletion,
  placement,
  firstMatchOfDay,
  mission,
  rewardedAd,
  shopPurchase,
  adjustment,
}

@immutable
class CurrencyEvent implements GameAnalyticsEvent {
  const CurrencyEvent({
    required this.flow,
    required this.source,
    required this.amount,
    this.balanceAfter,
    this.anonymousTransactionId,
    this.match,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(amount > 0),
       assert(balanceAfter == null || balanceAfter >= 0);

  final CurrencyFlow flow;
  final CurrencySource source;
  final int amount;
  final int? balanceAfter;
  final String? anonymousTransactionId;
  final MatchAnalyticsContext? match;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (flow) {
    CurrencyFlow.earned => 'currency_earned',
    CurrencyFlow.spent => 'currency_spent',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...correlation.parameters,
      if (match case final value?) ...value.parameters,
      'currency_source': source.name,
      'coin_amount': amount,
    };
    if (balanceAfter case final value?) {
      result['balance_after'] = value;
    }
    if (anonymousTransactionId case final value?) {
      result['transaction_ref'] = _validatedAnonymousReference(
        value,
        'anonymousTransactionId',
      );
    }
    return result;
  }
}

enum ShopStage { previewed, purchased, equipped }

enum ShopProductType { theme, dice, tokens, avatar, bundle }

@immutable
class ShopEvent implements GameAnalyticsEvent {
  const ShopEvent({
    required this.stage,
    required this.productId,
    required this.productType,
    this.priceCoins,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(priceCoins == null || priceCoins >= 0),
       assert(
         stage != ShopStage.purchased || priceCoins != null,
         'A purchase must include its coin price.',
       );

  final ShopStage stage;
  final String productId;
  final ShopProductType productType;
  final int? priceCoins;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (stage) {
    ShopStage.previewed => 'shop_previewed',
    ShopStage.purchased => 'shop_purchased',
    ShopStage.equipped => 'shop_equipped',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...correlation.parameters,
      'product_id': _validatedCatalogIdentifier(productId),
      'product_type': productType.name,
    };
    if (priceCoins case final value?) {
      result['price_coins'] = value;
    }
    return result;
  }
}

/// The original analytics API used throughout the application.
///
/// This contract intentionally keeps its single original method so existing
/// callers and test doubles continue to compile while the migration to typed
/// events is rolled out incrementally.
abstract interface class GameAnalytics {
  Future<void> logMatchStarted(MatchStartEvent event);
}

/// The richer analytics contract implemented by production and no-op loggers.
abstract interface class TypedGameAnalytics implements GameAnalytics {
  Future<void> logEvent(GameAnalyticsEvent event);
}

/// Lets code that still receives [GameAnalytics] send new typed events safely.
///
/// Legacy implementations ignore new event types, but continue to receive
/// [MatchStartEvent] through the original API.
extension TypedGameAnalyticsCompatibility on GameAnalytics {
  Future<void> logEvent(GameAnalyticsEvent event) {
    final analytics = this;
    if (analytics is TypedGameAnalytics) {
      return analytics.logEvent(event);
    }
    if (event is MatchStartEvent) {
      return analytics.logMatchStarted(event);
    }
    return Future<void>.value();
  }
}

/// Minimal destination abstraction for deterministic analytics tests.
abstract interface class GameAnalyticsSink {
  Future<void> log({
    required String eventName,
    required Map<String, Object> parameters,
  });
}

class NoopGameAnalytics implements TypedGameAnalytics {
  const NoopGameAnalytics();

  @override
  Future<void> logEvent(GameAnalyticsEvent event) async {}

  @override
  Future<void> logMatchStarted(MatchStartEvent event) async {}
}

/// Analytics implementation that accepts an injectable destination.
///
/// Logging errors are contained here so analytics can never interrupt a match.
class SinkGameAnalytics implements TypedGameAnalytics {
  const SinkGameAnalytics(this._sink);

  final GameAnalyticsSink _sink;

  @override
  Future<void> logMatchStarted(MatchStartEvent event) => logEvent(event);

  @override
  Future<void> logEvent(GameAnalyticsEvent event) async {
    try {
      final parameters = event.parameters;
      _validateAnalyticsPayload(event.eventName, parameters);
      await _sink.log(eventName: event.eventName, parameters: parameters);
    } catch (error, stackTrace) {
      // Do not interpolate the event name, rejected parameter value, or error
      // text here. Validation errors can originate from accidental PII, and
      // ArgumentError.toString() normally includes its rejected value.
      debugPrint('Analytics event was not recorded (${error.runtimeType}).');
      debugPrintStack(stackTrace: stackTrace);
    }
  }
}

class FirebaseGameAnalytics extends SinkGameAnalytics {
  FirebaseGameAnalytics(FirebaseAnalytics analytics)
    : super(_FirebaseGameAnalyticsSink(analytics));
}

class _FirebaseGameAnalyticsSink implements GameAnalyticsSink {
  const _FirebaseGameAnalyticsSink(this._analytics);

  final FirebaseAnalytics _analytics;

  @override
  Future<void> log({
    required String eventName,
    required Map<String, Object> parameters,
  }) {
    return _analytics.logEvent(name: eventName, parameters: parameters);
  }
}

Future<GameAnalytics> initializeGameAnalytics() async {
  if (kIsWeb ||
      (defaultTargetPlatform != TargetPlatform.android &&
          defaultTargetPlatform != TargetPlatform.iOS &&
          defaultTargetPlatform != TargetPlatform.macOS)) {
    return const NoopGameAnalytics();
  }

  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
    return FirebaseGameAnalytics(FirebaseAnalytics.instance);
  } catch (error, stackTrace) {
    debugPrint('Google Analytics initialization was skipped: $error');
    debugPrintStack(stackTrace: stackTrace);
    return const NoopGameAnalytics();
  }
}

String _gameModeName(GameMode mode) => switch (mode) {
  GameMode.traditional => 'traditional',
  GameMode.chaos => 'chaos',
};

String _validatedAnonymousReference(String value, String argumentName) {
  final kind = switch (argumentName) {
    'anonymousMatchId' => _AnonymousReferenceKind.match,
    'anonymousSessionId' => _AnonymousReferenceKind.session,
    'anonymousTransactionId' => _AnonymousReferenceKind.transaction,
    _ => null,
  };
  if (kind == null || !_isOpaqueAnonymousReference(value, kind)) {
    throw ArgumentError(
      'Must be an app-generated opaque analytics reference.',
      argumentName,
    );
  }
  return value;
}

String _validatedCatalogIdentifier(String value) {
  if (!_isSafeIdentifier(value, maximumLength: 64)) {
    throw ArgumentError('Must be a valid catalog identifier.', 'productId');
  }
  return value;
}

enum _AnonymousReferenceKind { match, session, transaction }

const Map<_AnonymousReferenceKind, List<String>> _anonymousReferencePrefixes =
    <_AnonymousReferenceKind, List<String>>{
      _AnonymousReferenceKind.match: <String>[
        'match_',
        'cpu_match_',
        'online_match_',
        'restored_match_',
        'resume_match_',
        'resume_',
        'quick-',
      ],
      _AnonymousReferenceKind.session: <String>['session_', 'shop_session_'],
      _AnonymousReferenceKind.transaction: <String>[
        'transaction_',
        'reward_transaction_',
        'shop_transaction_',
      ],
    };

bool _isOpaqueAnonymousReference(String value, _AnonymousReferenceKind kind) {
  if (!_isSafeIdentifier(value, maximumLength: 64)) return false;
  return _anonymousReferencePrefixes[kind]!.any(
    (prefix) => value.startsWith(prefix) && value.length > prefix.length,
  );
}

bool _isSafeIdentifier(String value, {required int maximumLength}) {
  if (value.isEmpty || value.length > maximumLength) return false;
  for (final codeUnit in value.codeUnits) {
    final isDigit = codeUnit >= 48 && codeUnit <= 57;
    final isUppercase = codeUnit >= 65 && codeUnit <= 90;
    final isLowercase = codeUnit >= 97 && codeUnit <= 122;
    final isSeparator = codeUnit == 45 || codeUnit == 95;
    if (!isDigit && !isUppercase && !isLowercase && !isSeparator) {
      return false;
    }
  }
  return true;
}

const Set<String> _allowedParameterNames = <String>{
  'abandon_reason',
  'ad_placement',
  'app_session_ref',
  'balance_after',
  'coin_amount',
  'completion_reason',
  'cpu_difficulty',
  'currency_source',
  'dice_count',
  'duration_seconds',
  'elapsed_seconds',
  'fallback_opponent_count',
  'game_mode',
  'is_rematch',
  'launch_source',
  'live_human_opponent_count',
  'match_ref',
  'matchmaking_wait_seconds',
  'placement',
  'play_type',
  'price_coins',
  'product_id',
  'product_type',
  'resume_failure_reason',
  'reward_coins',
  'seconds_away',
  'seconds_from_match_start',
  'seconds_played',
  'taken_over_opponent_count',
  'transaction_ref',
  'turn_number',
  'turns_played',
  'tutorial_step',
};

void _validateAnalyticsPayload(
  String eventName,
  Map<String, Object> parameters,
) {
  if (eventName.isEmpty ||
      eventName.length > 40 ||
      !_isSafeIdentifier(eventName, maximumLength: 40) ||
      eventName.startsWith('firebase_') ||
      eventName.startsWith('google_') ||
      eventName.startsWith('ga_')) {
    throw ArgumentError('Invalid analytics event name.', 'eventName');
  }
  if (parameters.length > 25) {
    throw ArgumentError(
      'Analytics payload exceeds the parameter limit.',
      'parameters',
    );
  }
  for (final entry in parameters.entries) {
    if (!_allowedParameterNames.contains(entry.key)) {
      throw ArgumentError(
        'Analytics payload contains a parameter outside the allowlist.',
        'parameters',
      );
    }
    final value = entry.value;
    if (value is! String && value is! int && value is! double) {
      throw ArgumentError(
        'Analytics payload contains an unsupported value type.',
        'parameters',
      );
    }
    if (value is String && value.length > 100) {
      throw ArgumentError(
        'Analytics payload contains an oversized string value.',
        'parameters',
      );
    }
    final referenceKind = switch (entry.key) {
      'match_ref' => _AnonymousReferenceKind.match,
      'app_session_ref' => _AnonymousReferenceKind.session,
      'transaction_ref' => _AnonymousReferenceKind.transaction,
      _ => null,
    };
    if (referenceKind != null &&
        (value is! String ||
            !_isOpaqueAnonymousReference(value, referenceKind))) {
      throw ArgumentError(
        'Analytics payload contains an invalid opaque reference.',
        'parameters',
      );
    }
    if (entry.key == 'product_id' &&
        (value is! String || !_isSafeIdentifier(value, maximumLength: 64))) {
      throw ArgumentError(
        'Analytics payload contains an invalid catalog identifier.',
        'parameters',
      );
    }
  }
}
