import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'firebase_options.dart';
import 'game_engine.dart';

enum MatchPlayType { online, cpu }

enum MatchLaunchSource { home, rematch }

enum CpuDifficulty { easy, normal, expert }

enum OnlineExperience { quickPop, quickTable }

enum OnlineFlowStage {
  entryOpened,
  entryCancelled,
  connectionFailed,
  searchStarted,
  searchCancelled,
  searchFailed,
  playerFound,
  cpuFallback,
  settlementUnavailable,
  matchOpenFailed,
  createStarted,
  roomCreated,
  createCancelled,
  createFailed,
  joinStarted,
  roomJoined,
  joinCancelled,
  joinFailed,
  inviteShared,
  inviteShareCancelled,
  inviteShareFailed,
}

enum OnlineJoinMethod { roomCode, publicDirectory, invitation }

enum OnlineRoomAccess { private, public }

enum OnlineFlowFailureReason {
  network,
  permission,
  configuration,
  timeout,
  cancelled,
  invalidInput,
  roomFull,
  roomClosed,
  synchronization,
  unavailable,
  unknown,
}

enum RetentionMilestone { day0, day1, day7, returning }

int onlineSearchElapsedMilliseconds({
  required DateTime startedAt,
  required DateTime now,
}) {
  final elapsed = now.difference(startedAt).inMilliseconds;
  return elapsed < 0 ? 0 : elapsed;
}

int onlineMatchmakingWaitSeconds(int elapsedMilliseconds) {
  if (elapsedMilliseconds <= 0) return 0;
  return (elapsedMilliseconds / 1000).round();
}

/// Optional opaque references used to correlate anonymous analytics events.
///
/// These values must be generated by the app. They must never contain an email,
/// player name, phone number, advertising identifier, or Firebase user id. They
/// are intentionally logged as event parameters instead of user properties.
@immutable
class AnalyticsCorrelation {
  const AnalyticsCorrelation({this.anonymousMatchId, this.anonymousSessionId});

  final String? anonymousMatchId;
  final String? anonymousSessionId;

  Map<String, Object> get parameters {
    final result = <String, Object>{};
    if (anonymousMatchId case final value?) {
      result['match_ref'] = _validatedAnonymousReference(
        value,
        'anonymousMatchId',
      );
    }
    if (anonymousSessionId case final value?) {
      result['app_session_ref'] = _validatedAnonymousReference(
        value,
        'anonymousSessionId',
      );
    }
    return result;
  }
}

/// Shared, non-identifying context for events that belong to a match.
@immutable
class MatchAnalyticsContext {
  const MatchAnalyticsContext({
    required this.playType,
    required this.mode,
    this.matchFormat,
    this.correlation = const AnalyticsCorrelation(),
  });

  final MatchPlayType playType;
  final GameMode mode;
  final MatchFormat? matchFormat;
  final AnalyticsCorrelation correlation;

  Map<String, Object> get parameters => <String, Object>{
    'play_type': playType.name,
    'game_mode': _gameModeName(mode),
    if (matchFormat case final value?) 'match_format': value.name,
    ...correlation.parameters,
  };
}

/// A typed event that can be sent to the game's analytics destination.
abstract interface class GameAnalyticsEvent {
  String get eventName;

  Map<String, Object> get parameters;
}

/// One anonymous step in the Quick Pop or Quick Table online funnel.
///
/// The event deliberately accepts only enums, numeric elapsed time and the
/// existing opaque correlation references. Room codes, player names, Firebase
/// UIDs and raw exception messages have no place in this payload.
@immutable
class OnlineFlowEvent implements GameAnalyticsEvent {
  const OnlineFlowEvent({
    required this.experience,
    required this.stage,
    this.launchSource = MatchLaunchSource.home,
    this.elapsedMilliseconds,
    this.joinMethod,
    this.failureReason,
    this.roomAccess,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(elapsedMilliseconds == null || elapsedMilliseconds >= 0);

  final OnlineExperience experience;
  final OnlineFlowStage stage;
  final MatchLaunchSource launchSource;
  final int? elapsedMilliseconds;
  final OnlineJoinMethod? joinMethod;
  final OnlineFlowFailureReason? failureReason;
  final OnlineRoomAccess? roomAccess;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => _onlineFlowEventName(experience, stage);

  @override
  Map<String, Object> get parameters => <String, Object>{
    'online_experience': experience.name,
    'flow_stage': stage.name,
    'launch_source': launchSource.name,
    'elapsed_milliseconds': ?elapsedMilliseconds,
    if (joinMethod case final value?) 'join_method': value.name,
    if (failureReason case final value?) 'failure_reason': value.name,
    if (roomAccess case final value?) 'room_access': value.name,
    ...correlation.parameters,
  };
}

@immutable
class AppSessionStartedEvent implements GameAnalyticsEvent {
  const AppSessionStartedEvent({
    required this.daysSinceFirstSeen,
    required this.milestone,
    required this.isFirstAnalyticsSession,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(daysSinceFirstSeen >= 0);

  final int daysSinceFirstSeen;
  final RetentionMilestone milestone;
  final bool isFirstAnalyticsSession;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => 'app_session_started';

  @override
  Map<String, Object> get parameters => <String, Object>{
    'days_since_first_seen': daysSinceFirstSeen,
    'retention_milestone': milestone.name,
    'is_first_analytics_session': isFirstAnalyticsSession ? 1 : 0,
    ...correlation.parameters,
  };
}

String _onlineFlowEventName(
  OnlineExperience experience,
  OnlineFlowStage stage,
) {
  final prefix = switch (experience) {
    OnlineExperience.quickPop => 'quick_pop',
    OnlineExperience.quickTable => 'quick_table',
  };
  final suffix = switch (stage) {
    OnlineFlowStage.entryOpened => 'entry_opened',
    OnlineFlowStage.entryCancelled => 'entry_cancelled',
    OnlineFlowStage.connectionFailed => 'connection_failed',
    OnlineFlowStage.searchStarted => 'search_started',
    OnlineFlowStage.searchCancelled => 'search_cancelled',
    OnlineFlowStage.searchFailed => 'search_failed',
    OnlineFlowStage.playerFound => 'player_found',
    OnlineFlowStage.cpuFallback => 'cpu_fallback',
    OnlineFlowStage.settlementUnavailable => 'settlement_unavailable',
    OnlineFlowStage.matchOpenFailed => 'match_open_failed',
    OnlineFlowStage.createStarted => 'create_started',
    OnlineFlowStage.roomCreated => 'room_created',
    OnlineFlowStage.createCancelled => 'create_cancelled',
    OnlineFlowStage.createFailed => 'create_failed',
    OnlineFlowStage.joinStarted => 'join_started',
    OnlineFlowStage.roomJoined => 'room_joined',
    OnlineFlowStage.joinCancelled => 'join_cancelled',
    OnlineFlowStage.joinFailed => 'join_failed',
    OnlineFlowStage.inviteShared => 'invite_shared',
    OnlineFlowStage.inviteShareCancelled => 'invite_share_cancelled',
    OnlineFlowStage.inviteShareFailed => 'invite_share_failed',
  };
  return '${prefix}_$suffix';
}

@immutable
class MatchStartEvent implements GameAnalyticsEvent {
  const MatchStartEvent({
    required this.playType,
    required this.mode,
    this.matchFormat,
    this.launchSource = MatchLaunchSource.home,
    this.cpuDifficulty,
    this.matchmakingWaitSeconds,
    this.fallbackOpponentCount,
    this.liveHumanOpponentCount,
    this.takenOverOpponentCount,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(
         playType == MatchPlayType.cpu || cpuDifficulty == null,
         'Online matches cannot include a CPU difficulty.',
       ),
       assert(
         playType == MatchPlayType.online ||
             (matchmakingWaitSeconds == null &&
                 fallbackOpponentCount == null &&
                 liveHumanOpponentCount == null &&
                 takenOverOpponentCount == null),
         'CPU matches cannot include online matchmaking metrics.',
       ),
       assert(matchmakingWaitSeconds == null || matchmakingWaitSeconds >= 0),
       assert(fallbackOpponentCount == null || fallbackOpponentCount >= 0),
       assert(liveHumanOpponentCount == null || liveHumanOpponentCount >= 0),
       assert(takenOverOpponentCount == null || takenOverOpponentCount >= 0);

  final MatchPlayType playType;
  final GameMode mode;
  final MatchFormat? matchFormat;
  final MatchLaunchSource launchSource;
  final CpuDifficulty? cpuDifficulty;
  final int? matchmakingWaitSeconds;
  final int? fallbackOpponentCount;
  final int? liveHumanOpponentCount;
  final int? takenOverOpponentCount;
  final AnalyticsCorrelation correlation;

  bool get isRematch => launchSource == MatchLaunchSource.rematch;

  @override
  String get eventName => switch (playType) {
    MatchPlayType.online => 'online_match_started',
    MatchPlayType.cpu => 'cpu_match_started',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      'play_type': playType.name,
      'game_mode': _gameModeName(mode),
      if (matchFormat case final value?) 'match_format': value.name,
      'is_rematch': isRematch ? 1 : 0,
      'launch_source': launchSource.name,
      ...correlation.parameters,
    };
    if (cpuDifficulty case final value?) {
      result['cpu_difficulty'] = value.name;
    }
    if (matchmakingWaitSeconds case final value?) {
      result['matchmaking_wait_seconds'] = value;
    }
    if (fallbackOpponentCount case final value?) {
      result['fallback_opponent_count'] = value;
    }
    if (liveHumanOpponentCount case final value?) {
      result['live_human_opponent_count'] = value;
    }
    if (takenOverOpponentCount case final value?) {
      result['taken_over_opponent_count'] = value;
    }
    return result;
  }
}

@immutable
class MatchFirstRollEvent implements GameAnalyticsEvent {
  const MatchFirstRollEvent({
    required this.match,
    required this.secondsFromMatchStart,
    this.turnNumber = 1,
    this.diceCount = 2,
  }) : assert(secondsFromMatchStart >= 0),
       assert(turnNumber > 0),
       assert(diceCount > 0);

  final MatchAnalyticsContext match;
  final int secondsFromMatchStart;
  final int turnNumber;
  final int diceCount;

  @override
  String get eventName => 'match_first_roll';

  @override
  Map<String, Object> get parameters => <String, Object>{
    ...match.parameters,
    'seconds_from_match_start': secondsFromMatchStart,
    'turn_number': turnNumber,
    'dice_count': diceCount,
  };
}

enum MatchCompletionReason { reachedHome, forfeit, timeout }

@immutable
class MatchCompletedEvent implements GameAnalyticsEvent {
  const MatchCompletedEvent({
    required this.match,
    required this.reason,
    this.placement,
    required this.durationSeconds,
    required this.turnsPlayed,
  }) : assert(placement == null || (placement >= 1 && placement <= 4)),
       assert(durationSeconds >= 0),
       assert(turnsPlayed >= 0);

  final MatchAnalyticsContext match;
  final MatchCompletionReason reason;
  final int? placement;
  final int durationSeconds;
  final int turnsPlayed;

  @override
  String get eventName => 'match_completed';

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...match.parameters,
      'completion_reason': reason.name,
      'duration_seconds': durationSeconds,
      'turns_played': turnsPlayed,
    };
    if (placement case final value?) result['placement'] = value;
    return result;
  }
}

enum MatchAbandonReason { backButton, appClosed, inactivity, disconnect, other }

@immutable
class MatchAbandonedEvent implements GameAnalyticsEvent {
  const MatchAbandonedEvent({
    required this.match,
    required this.reason,
    required this.secondsPlayed,
    required this.turnsPlayed,
  }) : assert(secondsPlayed >= 0),
       assert(turnsPlayed >= 0);

  final MatchAnalyticsContext match;
  final MatchAbandonReason reason;
  final int secondsPlayed;
  final int turnsPlayed;

  @override
  String get eventName => 'match_abandoned';

  @override
  Map<String, Object> get parameters => <String, Object>{
    ...match.parameters,
    'abandon_reason': reason.name,
    'seconds_played': secondsPlayed,
    'turns_played': turnsPlayed,
  };
}

enum MatchResumeStage { attempted, succeeded, failed }

enum MatchResumeFailureReason { missingSave, invalidSave, expired, other }

@immutable
class MatchResumeEvent implements GameAnalyticsEvent {
  const MatchResumeEvent({
    required this.match,
    required this.stage,
    this.secondsAway,
    this.failureReason,
  }) : assert(secondsAway == null || secondsAway >= 0),
       assert(
         stage == MatchResumeStage.failed || failureReason == null,
         'Only a failed resume can include a failure reason.',
       );

  final MatchAnalyticsContext match;
  final MatchResumeStage stage;
  final int? secondsAway;
  final MatchResumeFailureReason? failureReason;

  @override
  String get eventName => switch (stage) {
    MatchResumeStage.attempted => 'match_resume_attempted',
    MatchResumeStage.succeeded => 'match_resumed',
    MatchResumeStage.failed => 'match_resume_failed',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{...match.parameters};
    if (secondsAway case final value?) {
      result['seconds_away'] = value;
    }
    if (failureReason case final value?) {
      result['resume_failure_reason'] = value.name;
    }
    return result;
  }
}

enum RematchStage { offered, started, declined }

@immutable
class RematchEvent implements GameAnalyticsEvent {
  const RematchEvent({required this.match, required this.stage});

  final MatchAnalyticsContext match;
  final RematchStage stage;

  @override
  String get eventName => switch (stage) {
    RematchStage.offered => 'rematch_offered',
    RematchStage.started => 'rematch_started',
    RematchStage.declined => 'rematch_declined',
  };

  @override
  Map<String, Object> get parameters => match.parameters;
}

enum TutorialStage { started, stepCompleted, skipped, completed }

enum TutorialStep {
  firstRoll,
  releaseToken,
  chooseMove,
  safeSquare,
  capture,
  reachHome,
}

@immutable
class TutorialEvent implements GameAnalyticsEvent {
  const TutorialEvent({
    required this.stage,
    this.step,
    this.elapsedSeconds,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(elapsedSeconds == null || elapsedSeconds >= 0),
       assert(
         stage != TutorialStage.stepCompleted || step != null,
         'A completed tutorial step must identify the step.',
       );

  final TutorialStage stage;
  final TutorialStep? step;
  final int? elapsedSeconds;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (stage) {
    TutorialStage.started => 'tutorial_started',
    TutorialStage.stepCompleted => 'tutorial_step_completed',
    TutorialStage.skipped => 'tutorial_skipped',
    TutorialStage.completed => 'tutorial_completed',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{...correlation.parameters};
    if (step case final value?) {
      result['tutorial_step'] = value.name;
    }
    if (elapsedSeconds case final value?) {
      result['elapsed_seconds'] = value;
    }
    return result;
  }
}

enum RewardedAdStage {
  offered,
  started,
  completed,
  declined,
  unavailable,
  failed,
}

enum RewardedAdPlacement { shopCoins, postMatchReward }

@immutable
class RewardedAdEvent implements GameAnalyticsEvent {
  const RewardedAdEvent({
    required this.stage,
    required this.placement,
    this.rewardCoins,
    this.match,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(rewardCoins == null || rewardCoins > 0);

  final RewardedAdStage stage;
  final RewardedAdPlacement placement;
  final int? rewardCoins;
  final MatchAnalyticsContext? match;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (stage) {
    RewardedAdStage.offered => 'rewarded_ad_offered',
    RewardedAdStage.started => 'rewarded_ad_started',
    RewardedAdStage.completed => 'rewarded_ad_completed',
    RewardedAdStage.declined => 'rewarded_ad_declined',
    RewardedAdStage.unavailable => 'rewarded_ad_unavailable',
    RewardedAdStage.failed => 'rewarded_ad_failed',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...correlation.parameters,
      if (match case final value?) ...value.parameters,
      'ad_placement': placement.name,
    };
    if (rewardCoins case final value?) {
      result['reward_coins'] = value;
    }
    return result;
  }
}

enum CurrencyFlow { earned, spent }

enum CurrencySource {
  matchCompletion,
  placement,
  firstMatchOfDay,
  mission,
  rewardedAd,
  shopPurchase,
  adjustment,
}

@immutable
class CurrencyEvent implements GameAnalyticsEvent {
  const CurrencyEvent({
    required this.flow,
    required this.source,
    required this.amount,
    this.balanceBefore,
    this.balanceAfter,
    this.anonymousTransactionId,
    this.match,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(amount > 0),
       assert(balanceBefore == null || balanceBefore >= 0),
       assert(balanceAfter == null || balanceAfter >= 0),
       assert(
         balanceBefore == null ||
             balanceAfter == null ||
             (flow == CurrencyFlow.earned
                 ? balanceAfter == balanceBefore + amount
                 : balanceAfter == balanceBefore - amount),
         'Currency balances must reconcile with the event flow and amount.',
       );

  final CurrencyFlow flow;
  final CurrencySource source;
  final int amount;
  final int? balanceBefore;
  final int? balanceAfter;
  final String? anonymousTransactionId;
  final MatchAnalyticsContext? match;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (flow) {
    CurrencyFlow.earned => 'currency_earned',
    CurrencyFlow.spent => 'currency_spent',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...correlation.parameters,
      if (match case final value?) ...value.parameters,
      'currency_source': source.name,
      'coin_amount': amount,
    };
    if (balanceBefore case final value?) {
      result['balance_before'] = value;
    }
    if (balanceAfter case final value?) {
      result['balance_after'] = value;
    }
    if (anonymousTransactionId case final value?) {
      result['transaction_ref'] = _validatedAnonymousReference(
        value,
        'anonymousTransactionId',
      );
    }
    return result;
  }
}

enum MissionKind {
  move20Cells,
  releaseToken,
  finishOneMatch,
  sharedTableTurns,
  sharedTableMatch,
  quickPopMatches,
  chaosMatch,
  welcomeMission,
  finish7Matches,
}

@immutable
class MissionRewardEvent implements GameAnalyticsEvent {
  const MissionRewardEvent({
    required this.mission,
    required this.rewardCoins,
    required this.progress,
    required this.target,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(rewardCoins > 0),
       assert(progress >= 0),
       assert(target > 0);

  final MissionKind mission;
  final int rewardCoins;
  final int progress;
  final int target;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => 'mission_rewarded';

  @override
  Map<String, Object> get parameters => <String, Object>{
    ...correlation.parameters,
    'mission_id': mission.name,
    'mission_progress': progress,
    'mission_target': target,
    'reward_coins': rewardCoins,
  };
}

enum ShopStage { previewed, purchased, equipped }

enum ShopProductType { theme, dice, tokens, avatar, bundle }

@immutable
class ShopEvent implements GameAnalyticsEvent {
  const ShopEvent({
    required this.stage,
    required this.productId,
    required this.productType,
    this.priceCoins,
    this.correlation = const AnalyticsCorrelation(),
  }) : assert(priceCoins == null || priceCoins >= 0),
       assert(
         stage != ShopStage.purchased || priceCoins != null,
         'A purchase must include its coin price.',
       );

  final ShopStage stage;
  final String productId;
  final ShopProductType productType;
  final int? priceCoins;
  final AnalyticsCorrelation correlation;

  @override
  String get eventName => switch (stage) {
    ShopStage.previewed => 'shop_previewed',
    ShopStage.purchased => 'shop_purchased',
    ShopStage.equipped => 'shop_equipped',
  };

  @override
  Map<String, Object> get parameters {
    final result = <String, Object>{
      ...correlation.parameters,
      'product_id': _validatedCatalogIdentifier(productId),
      'product_type': productType.name,
    };
    if (priceCoins case final value?) {
      result['price_coins'] = value;
    }
    return result;
  }
}

/// The original analytics API used throughout the application.
///
/// This contract intentionally keeps its single original method so existing
/// callers and test doubles continue to compile while the migration to typed
/// events is rolled out incrementally.
abstract interface class GameAnalytics {
  Future<void> logMatchStarted(MatchStartEvent event);
}

/// The richer analytics contract implemented by production and no-op loggers.
abstract interface class TypedGameAnalytics implements GameAnalytics {
  Future<void> logEvent(GameAnalyticsEvent event);
}

const String analyticsCollectionPreferenceKey =
    'privacy_analytics_collection_enabled';
const String analyticsFirstSeenAtPreferenceKey = 'analytics_first_seen_at_ms';
const String analyticsLastSessionAtPreferenceKey =
    'analytics_last_session_at_ms';

/// Records a 30-minute anonymous app session for opted-in players.
///
/// The first-seen timestamp stays on the device and is used only to derive a
/// coarse D1/D7 retention milestone. Collection remains strictly opt-in: when
/// [analytics] does not expose an enabled [AnalyticsPrivacyControl], no event
/// and no last-session marker are written.
Future<void> recordAppSessionAnalytics(
  GameAnalytics analytics, {
  required String anonymousSessionId,
  SharedPreferences? preferences,
  DateTime? now,
}) async {
  try {
    await _recordAppSessionAnalytics(
      analytics,
      anonymousSessionId: anonymousSessionId,
      preferences: preferences,
      now: now,
    );
  } catch (error, stackTrace) {
    // Session measurement must never delay or prevent the app from opening.
    // Keep diagnostics generic because storage errors can include local paths.
    debugPrint(
      'Anonymous session analytics was skipped (${error.runtimeType}).',
    );
    debugPrintStack(stackTrace: stackTrace);
  }
}

Future<void> _recordAppSessionAnalytics(
  GameAnalytics analytics, {
  required String anonymousSessionId,
  SharedPreferences? preferences,
  DateTime? now,
}) async {
  final store = preferences ?? await SharedPreferences.getInstance();
  final moment = (now ?? DateTime.now()).toUtc();
  var firstSeenAtMs = store.getInt(analyticsFirstSeenAtPreferenceKey);
  if (firstSeenAtMs == null || firstSeenAtMs > moment.millisecondsSinceEpoch) {
    firstSeenAtMs = moment.millisecondsSinceEpoch;
    await store.setInt(analyticsFirstSeenAtPreferenceKey, firstSeenAtMs);
  }

  // Session delivery fails closed. A no-op or legacy logger cannot prove that
  // collection is both available and explicitly enabled, so it must not write
  // the last-session idempotency marker either.
  final AnalyticsPrivacyControl? privacyControl =
      analytics is AnalyticsPrivacyControl
      ? analytics as AnalyticsPrivacyControl
      : null;
  if (privacyControl == null || !privacyControl.analyticsCollectionEnabled) {
    return;
  }

  final lastSessionAtMs = store.getInt(analyticsLastSessionAtPreferenceKey);
  if (lastSessionAtMs != null) {
    final timeSinceLastSession = moment.difference(
      DateTime.fromMillisecondsSinceEpoch(lastSessionAtMs, isUtc: true),
    );
    if (!timeSinceLastSession.isNegative &&
        timeSinceLastSession < const Duration(minutes: 30)) {
      return;
    }
  }

  final firstSeen = DateTime.fromMillisecondsSinceEpoch(
    firstSeenAtMs,
    isUtc: true,
  );
  final firstSeenDay = DateTime.utc(
    firstSeen.year,
    firstSeen.month,
    firstSeen.day,
  );
  final currentDay = DateTime.utc(moment.year, moment.month, moment.day);
  final daysSinceFirstSeen = currentDay.difference(firstSeenDay).inDays;
  final milestone = switch (daysSinceFirstSeen) {
    0 => RetentionMilestone.day0,
    1 => RetentionMilestone.day1,
    7 => RetentionMilestone.day7,
    _ => RetentionMilestone.returning,
  };
  await analytics.logEvent(
    AppSessionStartedEvent(
      daysSinceFirstSeen: daysSinceFirstSeen,
      milestone: milestone,
      isFirstAnalyticsSession: lastSessionAtMs == null,
      correlation: AnalyticsCorrelation(anonymousSessionId: anonymousSessionId),
    ),
  );
  await store.setInt(
    analyticsLastSessionAtPreferenceKey,
    moment.millisecondsSinceEpoch,
  );
}

/// Explicit opt-in control for anonymous product analytics.
///
/// Collection defaults to off. Advertising consent is intentionally separate
/// because declining analytics must never affect the ability to play or to
/// manage AdMob privacy choices.
abstract interface class AnalyticsPrivacyControl {
  bool get analyticsCollectionEnabled;

  Future<void> setAnalyticsCollectionEnabled(bool enabled);
}

typedef AnalyticsCollectionApplier = Future<void> Function(bool enabled);

class ConsentManagedGameAnalytics
    implements TypedGameAnalytics, AnalyticsPrivacyControl {
  ConsentManagedGameAnalytics({
    required GameAnalytics delegate,
    required SharedPreferences preferences,
    required bool enabled,
    AnalyticsCollectionApplier? applyPlatformCollection,
  }) : _delegate = delegate,
       _preferences = preferences,
       _enabled = enabled,
       _applyPlatformCollection =
           applyPlatformCollection ?? ((_) => Future<void>.value());

  final GameAnalytics _delegate;
  final SharedPreferences _preferences;
  final AnalyticsCollectionApplier _applyPlatformCollection;
  bool _enabled;

  @override
  bool get analyticsCollectionEnabled => _enabled;

  @override
  Future<void> setAnalyticsCollectionEnabled(bool enabled) async {
    if (_enabled == enabled) return;
    await _applyPlatformCollection(enabled);
    final saved = await _preferences.setBool(
      analyticsCollectionPreferenceKey,
      enabled,
    );
    if (!saved) {
      await _applyPlatformCollection(_enabled);
      throw StateError('Analytics privacy preference was not persisted.');
    }
    _enabled = enabled;
  }

  @override
  Future<void> logEvent(GameAnalyticsEvent event) =>
      _enabled ? _delegate.logEvent(event) : Future<void>.value();

  @override
  Future<void> logMatchStarted(MatchStartEvent event) =>
      _enabled ? _delegate.logMatchStarted(event) : Future<void>.value();
}

/// Lets code that still receives [GameAnalytics] send new typed events safely.
///
/// Legacy implementations ignore new event types, but continue to receive
/// [MatchStartEvent] through the original API.
extension TypedGameAnalyticsCompatibility on GameAnalytics {
  Future<void> logEvent(GameAnalyticsEvent event) {
    final analytics = this;
    if (analytics is TypedGameAnalytics) {
      return analytics.logEvent(event);
    }
    if (event is MatchStartEvent) {
      return analytics.logMatchStarted(event);
    }
    return Future<void>.value();
  }
}

/// Minimal destination abstraction for deterministic analytics tests.
abstract interface class GameAnalyticsSink {
  Future<void> log({
    required String eventName,
    required Map<String, Object> parameters,
  });
}

class NoopGameAnalytics implements TypedGameAnalytics {
  const NoopGameAnalytics();

  @override
  Future<void> logEvent(GameAnalyticsEvent event) async {}

  @override
  Future<void> logMatchStarted(MatchStartEvent event) async {}
}

/// Analytics implementation that accepts an injectable destination.
///
/// Logging errors are contained here so analytics can never interrupt a match.
class SinkGameAnalytics implements TypedGameAnalytics {
  const SinkGameAnalytics(this._sink);

  final GameAnalyticsSink _sink;

  @override
  Future<void> logMatchStarted(MatchStartEvent event) => logEvent(event);

  @override
  Future<void> logEvent(GameAnalyticsEvent event) async {
    try {
      final parameters = event.parameters;
      _validateAnalyticsPayload(event.eventName, parameters);
      await _sink.log(eventName: event.eventName, parameters: parameters);
    } catch (error, stackTrace) {
      // Do not interpolate the event name, rejected parameter value, or error
      // text here. Validation errors can originate from accidental PII, and
      // ArgumentError.toString() normally includes its rejected value.
      debugPrint('Analytics event was not recorded (${error.runtimeType}).');
      debugPrintStack(stackTrace: stackTrace);
    }
  }
}

class FirebaseGameAnalytics extends SinkGameAnalytics {
  FirebaseGameAnalytics(FirebaseAnalytics analytics)
    : super(_FirebaseGameAnalyticsSink(analytics));
}

class _FirebaseGameAnalyticsSink implements GameAnalyticsSink {
  const _FirebaseGameAnalyticsSink(this._analytics);

  final FirebaseAnalytics _analytics;

  @override
  Future<void> log({
    required String eventName,
    required Map<String, Object> parameters,
  }) {
    return _analytics.logEvent(name: eventName, parameters: parameters);
  }
}

Future<GameAnalytics> initializeGameAnalytics() async {
  if (kIsWeb ||
      (defaultTargetPlatform != TargetPlatform.android &&
          defaultTargetPlatform != TargetPlatform.iOS &&
          defaultTargetPlatform != TargetPlatform.macOS)) {
    return const NoopGameAnalytics();
  }

  try {
    final preferences = await SharedPreferences.getInstance();
    final collectionEnabled =
        preferences.getBool(analyticsCollectionPreferenceKey) ?? false;
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
    final firebaseAnalytics = FirebaseAnalytics.instance;
    await firebaseAnalytics.setAnalyticsCollectionEnabled(collectionEnabled);
    return ConsentManagedGameAnalytics(
      delegate: FirebaseGameAnalytics(firebaseAnalytics),
      preferences: preferences,
      enabled: collectionEnabled,
      applyPlatformCollection: firebaseAnalytics.setAnalyticsCollectionEnabled,
    );
  } catch (error, stackTrace) {
    debugPrint('Google Analytics initialization was skipped: $error');
    debugPrintStack(stackTrace: stackTrace);
    return const NoopGameAnalytics();
  }
}

String _gameModeName(GameMode mode) => switch (mode) {
  GameMode.traditional => 'traditional',
  GameMode.chaos => 'chaos',
};

String _validatedAnonymousReference(String value, String argumentName) {
  final kind = switch (argumentName) {
    'anonymousMatchId' => _AnonymousReferenceKind.match,
    'anonymousSessionId' => _AnonymousReferenceKind.session,
    'anonymousTransactionId' => _AnonymousReferenceKind.transaction,
    _ => null,
  };
  if (kind == null || !_isOpaqueAnonymousReference(value, kind)) {
    throw ArgumentError(
      'Must be an app-generated opaque analytics reference.',
      argumentName,
    );
  }
  return value;
}

String _validatedCatalogIdentifier(String value) {
  if (!_isSafeIdentifier(value, maximumLength: 64)) {
    throw ArgumentError('Must be a valid catalog identifier.', 'productId');
  }
  return value;
}

enum _AnonymousReferenceKind { match, session, transaction }

const Map<_AnonymousReferenceKind, List<String>> _anonymousReferencePrefixes =
    <_AnonymousReferenceKind, List<String>>{
      _AnonymousReferenceKind.match: <String>[
        'match_',
        'cpu_match_',
        'online_match_',
        'restored_match_',
        'resume_match_',
        'resume_',
        'quick-',
      ],
      _AnonymousReferenceKind.session: <String>[
        'session_',
        'shop_session_',
        'tutorial_session_',
      ],
      _AnonymousReferenceKind.transaction: <String>[
        'transaction_',
        'reward_transaction_',
        'shop_transaction_',
      ],
    };

bool _isOpaqueAnonymousReference(String value, _AnonymousReferenceKind kind) {
  if (!_isSafeIdentifier(value, maximumLength: 64)) return false;
  return _anonymousReferencePrefixes[kind]!.any(
    (prefix) => value.startsWith(prefix) && value.length > prefix.length,
  );
}

bool _isSafeIdentifier(String value, {required int maximumLength}) {
  if (value.isEmpty || value.length > maximumLength) return false;
  for (final codeUnit in value.codeUnits) {
    final isDigit = codeUnit >= 48 && codeUnit <= 57;
    final isUppercase = codeUnit >= 65 && codeUnit <= 90;
    final isLowercase = codeUnit >= 97 && codeUnit <= 122;
    final isSeparator = codeUnit == 45 || codeUnit == 95;
    if (!isDigit && !isUppercase && !isLowercase && !isSeparator) {
      return false;
    }
  }
  return true;
}

const Set<String> _allowedParameterNames = <String>{
  'abandon_reason',
  'ad_placement',
  'app_session_ref',
  'balance_before',
  'balance_after',
  'coin_amount',
  'completion_reason',
  'cpu_difficulty',
  'currency_source',
  'days_since_first_seen',
  'dice_count',
  'duration_seconds',
  'elapsed_milliseconds',
  'elapsed_seconds',
  'fallback_opponent_count',
  'failure_reason',
  'flow_stage',
  'game_mode',
  'is_first_analytics_session',
  'is_rematch',
  'join_method',
  'launch_source',
  'live_human_opponent_count',
  'match_ref',
  'match_format',
  'matchmaking_wait_seconds',
  'mission_id',
  'mission_progress',
  'mission_target',
  'online_experience',
  'placement',
  'play_type',
  'price_coins',
  'product_id',
  'product_type',
  'resume_failure_reason',
  'reward_coins',
  'retention_milestone',
  'room_access',
  'seconds_away',
  'seconds_from_match_start',
  'seconds_played',
  'taken_over_opponent_count',
  'transaction_ref',
  'turn_number',
  'turns_played',
  'tutorial_step',
};

void _validateAnalyticsPayload(
  String eventName,
  Map<String, Object> parameters,
) {
  if (eventName.isEmpty ||
      eventName.length > 40 ||
      !_isSafeIdentifier(eventName, maximumLength: 40) ||
      eventName.startsWith('firebase_') ||
      eventName.startsWith('google_') ||
      eventName.startsWith('ga_')) {
    throw ArgumentError('Invalid analytics event name.', 'eventName');
  }
  if (parameters.length > 25) {
    throw ArgumentError(
      'Analytics payload exceeds the parameter limit.',
      'parameters',
    );
  }
  for (final entry in parameters.entries) {
    if (!_allowedParameterNames.contains(entry.key)) {
      throw ArgumentError(
        'Analytics payload contains a parameter outside the allowlist.',
        'parameters',
      );
    }
    final value = entry.value;
    if (value is! String && value is! int && value is! double) {
      throw ArgumentError(
        'Analytics payload contains an unsupported value type.',
        'parameters',
      );
    }
    if (value is String && value.length > 100) {
      throw ArgumentError(
        'Analytics payload contains an oversized string value.',
        'parameters',
      );
    }
    final referenceKind = switch (entry.key) {
      'match_ref' => _AnonymousReferenceKind.match,
      'app_session_ref' => _AnonymousReferenceKind.session,
      'transaction_ref' => _AnonymousReferenceKind.transaction,
      _ => null,
    };
    if (referenceKind != null &&
        (value is! String ||
            !_isOpaqueAnonymousReference(value, referenceKind))) {
      throw ArgumentError(
        'Analytics payload contains an invalid opaque reference.',
        'parameters',
      );
    }
    if (entry.key == 'product_id' &&
        (value is! String || !_isSafeIdentifier(value, maximumLength: 64))) {
      throw ArgumentError(
        'Analytics payload contains an invalid catalog identifier.',
        'parameters',
      );
    }
  }
}
